version: "3"

services:
  redis-compose:
    image: redis
    command: redis-server --requirepass root --appendonly yes
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis:/var/lib/postgresql/data
